KingstonHyperxBundle_admin_kingston_hyperx_bundle_Category:
    resource: "@KingstonHyperxBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /admin/category

KingstonHyperxBundle_admin_kingston_hyperx_bundle_Product:
    resource: "@KingstonHyperxBundle/Controller/Product/"
    type:     admingenerator
    prefix:   /admin/product

KingstonHyperxBundle_admin_kingston_hyperx_bundle_Review:
    resource: "@KingstonHyperxBundle/Controller/Review/"
    type:     admingenerator
    prefix:   /admin/review

KingstonHyperxBundle_admin_kingston_hyperx_bundle_Action:
    resource: "@KingstonHyperxBundle/Controller/Action/"
    type:     admingenerator
    prefix:   /admin/action

KingstonHyperxBundle_admin_kingston_hyperx_bundle_news:
    resource: "@KingstonHyperxBundle/Controller/News/"
    type:     admingenerator
    prefix:   /admin
kingston_hyperx:
    resource: "@KingstonHyperxBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
